### ISSUE TITLE
NanoCore: Another RAT tries to make it out of the gutter

### ISSUE THREAD

**Issue by ant1** [kbandla/APTnotes#109]
http://www.symantec.com/connect/blogs/nanocore-another-rat-tries-make-it-out-gutter

**Comment by kbandla** [comment]
PDF added in 90327472c6321fd06bbaf4ea18830a3255a9cec0

**Comment by mtmcgrew** [comment]
This is just talking about a specific RAT, they're not attributing use of the RAT to any group or APT actor.

**Comment by krmaxwell** [comment]
agree with @mtmcgrew - this isn't an espionage actor, just another rando RAT

**Comment by kbandla** [comment]
:+1: this can be dropped

**Comment by nyx0** [comment]
@krmaxwell I think you can close this issue too, thank you for merging by the way.

**Comment by krmaxwell** [comment]
oops forgot! thx!
