### ISSUE TITLE
AlienSpy Rat

### ISSUE THREAD

**Issue by ascendr** [kbandla/APTnotes#118]
Title: Fidelis Threat Advisory #1015  Ratting on AlienSpy
Date: Apr 08, 2015
Link: http://www.fidelissecurity.com/sites/default/files/FTA_1015_Alienspy_FINAL.pdf

**Comment by krmaxwell** [comment]
This is just code analysis, right? Not specifically an espionage actor? As with #109 I'm not sure this belongs in this particular listing.

**Comment by mtmcgrew** [comment]
Agreed with @krmaxwell. However, if there's any proof that some actor has used this RAT or builder(s) then that might be something else to consider.

**Comment by ascendr** [comment]
From the report: "AlienSpy is the latest in a family of RATs such as Adwind, Frutas and Unrecom, all of which have been observed in campaigns targeting large enterprises" 

.. I know frutas has been used by espionage actors, but not AlienSpy .. yet

**Comment by mtmcgrew** [comment]
Cool, i'm in favor of adding it then. While it may not be about a specific group, it's intel on TTPs used by groups.

**Comment by kbandla** [comment]
This sort of thing keeps coming up. Would it make sense to have a RAT section, with related analyses?

**Comment by mtmcgrew** [comment]
If we have enough reports of RATs used by actors then it would make sense. If we don't have a lot then it might make more sense to just put [RAT] or [TTP] in front of the report link.

On Apr 9, 2015, at 6:36 AM, kbandla <notifications@github.com<mailto:notifications@github.com>> wrote:


This sort of thing keeps coming up. Would it make sense to have a RAT section, with related analyses?

**Comment by kbandla** [comment]
Also see #155

**Comment by beast-fighter** [comment]
closing due to no relation to CE and/or APT - tagged and will be added at a later date (if deemed relevant) - just tool analysis not tied to a given campaign and/or actor
