### ISSUE TITLE
Classic Documents

### ISSUE THREAD

**Issue by chrisddom** [kbandla/APTnotes#12]
Hi,

 If you think some classic write-ups might be interesting from a historical perspective:

1986/1988 - http://pdf.textfiles.com/academics/wilyhacker.pdf (The Cuckoos Egg)
1999 - http://www.sfgate.com/news/article/Russians-Seem-To-Be-Hacking-Into-Pentagon-2903309.php / http://fas.org/irp/congress/2000_hr/030200_adams.htm (Moonlight Maze)
2004 - http://content.time.com/time/nation/article/0,8599,1098371,00.html / http://www.nytimes.com/2014/03/23/world/asia/nsa-breached-chinese-servers-seen-as-spy-peril.html?_r=0
2005 - (Note the classic comment crew domains) https://www.muckrock.com/foi/united-states-of-america-10/wauservdll-documents-department-of-energy-2950/#717599-doc_2_-_hq-2013-00590_redacted-pdf / https://www.muckrock.com/foi/united-states-of-america-10/wauservdll-documents-department-of-energy-2950/#717596-doc_1_-_hq-2013-00590_and_00591_redacted-pdf
2006 - http://krebsonsecurity.com/wp-content/uploads/2012/11/WickedRose_andNCPH.pdf

**Comment by beast-fighter** [comment]
all were added previously
