### ISSUE TITLE
Recent Sofacy / APT28 / Sednit

### ISSUE THREAD

**Issue by chrisddom** [kbandla/APTnotes#123]
These are more blog posts than full reports, so not sure how well they fit here but -

- http://blog.trendmicro.com/trendlabs-security-intelligence/operation-pawn-storm-ramps-up-its-activities-targets-nato-white-house/
- https://www.fireeye.com/blog/threat-research/2015/04/probable_apt28_useo.html
- http://pwc.blogs.com/files/cto-tib-20150420-01a.pdf (Full disclosure - I co-authored this and it's more of an indicator bulletin than a full report)

Whilst I'm here - I've included APT Notes data in a personal .org site ( see https://www.threatcrowd.org/browse.php ) - I hope that's ok and keep up the good work!

**Comment by kbandla** [comment]
@chrisddom thats totally okay! Its public information, so feel free to use it as you see fit.

**Comment by krmaxwell** [comment]
Is http://pwc.blogs.com/cyber_security_updates/2015/04/the-sofacy-plot-thickens.html part of the above, I guess?

**Comment by chrisddom** [comment]
Yup - that .html links to the .pdf
