### ISSUE TITLE
Presentation on Elise/Evora/Strunlib backdoor 

### ISSUE THREAD

**Issue by securitykitten** [kbandla/APTnotes#136]
http://anti-botnet.edu.tw/content/confs/BoT2013.PPTs/A1.php

This is a presentation from the TW botnet conference where the presenters were talking about the elise backdoor.  I'm not sure the public names for this group, but they are a well known APT set.

**Comment by nyx0** [comment]
In english is better :p https://media.blackhat.com/us-13/US-13-Yarochkin-In-Depth-Analysis-of-Escalated-APT-Attacks-Slides.pdf

**Comment by krmaxwell** [comment]
Thanks for the submission @securitykitten and @nyx0 is definitely right - :gb: is important for this particular project. :)

**Comment by securitykitten** [comment]
Holy cow, I didn't see the English one!  Thanks guys! :+1:

**Comment by kbandla** [comment]
Yeah, documents in english are desired. But sometimes, if the document is not available in english, and it has well documented IOCs, then we can perhaps add it.
Anyway, in this case, it looks like this presentation was added in bf3966e95f0f29f43171f694ac0656968d2996bd. Closing this issue. Thanks @nyx0 !
