### ISSUE TITLE
FireEye APT17 Report

### ISSUE THREAD

**Issue by srcr** [kbandla/APTnotes#146]
Might I suggest the FireEye APT17 report for inclusion.
https://www2.fireeye.com/rs/fireye/images/APT17_Report.pdf

**Comment by jpalanco** [comment]
This issue was closed here #137

(the url changed, but the pdf file is the same one)

Regards

**Comment by krmaxwell** [comment]
Yes, we decided that there was not nearly enough detail in this to warrant inclusion. Here's hoping they release something with more info on it soon! :)

**Comment by chrisddom** [comment]
Sorry to add to a closed issue - but talking of more info on this. A talk from earlier this year on this has been published today - https://www.youtube.com/watch?v=NFJqD-LcpIg&feature=youtu.be&t=26m24s - disclaimer I work with this dude

**Comment by krmaxwell** [comment]
Then here's hoping there's a full written report on them soon, would love
to see it! :D

On Sat, May 23, 2015 at 9:13 AM, chrisddom <notifications@github.com> wrote:

> Sorry to add to a closed issue - but talking of more info on this. A talk
> from earlier this year on this has been published today -
> https://www.youtube.com/watch?v=NFJqD-LcpIg&feature=youtu.be&t=26m24s -
> disclaimer I work with this dude
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbandla/APTnotes/issues/146#issuecomment-104901076>.
>



-- 
Kyle Maxwell [krmaxwell@gmail.com]
Twitter: @kylemaxwell
