### ISSUE TITLE
Report of OceanLotus APT

### ISSUE THREAD

**Issue by ftofficer** [kbandla/APTnotes#149]
https://skyeye.360safe.com/get_apt_pdf/kTAvH8mZuLfdclsD/OceanLotusReport.pdf

The report was published by Qihoo 360 SkyEye Labs, which describes an APT organization "OceanLotus" targeting China's ocean administration departments. The research was done by my colleagues.

The report is in Chinese, however.

**Comment by Neo23x0** [comment]
Server seems to be down.

**Comment by srcr** [comment]
Server is not down, but you need to give them your name, phone and mail address to download the direct link isn't working.
My opinion, a decent document with various IOC's/hashes that could be useful but the language is a big hurdle.

**Comment by chrisddom** [comment]
GET_APT_PDF eh :)

**Comment by srcr** [comment]
Got to love google translate: "puddles harpoon attack" aka spear phishing :)

**Comment by ftofficer** [comment]
Seems the report download links is randomly generated after registered emails. The direct links may not work. 

To download, open https://skyeye.360safe.com/ and click the middle picture with large "APT", register names and emails will get the latest download link.

Sorry for inconvenience.

**Comment by kbandla** [comment]
Added in 67dccacead3955e9cbab7b7bebfc0c710fed7e54. See commit log for hashes.

**Comment by kbandla** [comment]
Will post a google translated doc soon. So that we are consistent, and have the document in english. Will leave this issue open till then.

**Comment by beast-fighter** [comment]
any form of automated translation would not transfer to english well, closing out due to no English version availability
