### ISSUE TITLE
Operation Lotus Blossom

### ISSUE THREAD

**Issue by securitykitten** [kbandla/APTnotes#154]
https://www.paloaltonetworks.com/resources/research/unit42-operation-lotus-blossom.html

**Comment by srcr** [comment]
I find it interesting except for the management summary that could be skipped.

ioc after a quick scan

    SHA256 a28d6d7ac530753bb2ebfe1a9e9bd60269e6d227dec555e538cc36a6decf29f
    Campaign Code PYQ
    Command and Control 59.6.2.16
    cpcl2006.dyndns-free.com
    shotacon.dyndns.info
    petto.mooo.com
    kid.dyndns.org

    SHA256 949c9457a6c77e7e7f1519435149183c56eb53f7d74439fb848b5d6d91196a73
    Campaign Code PYQ
    Command and Control 59.6.2.16
    cpcl2006.dyndns-free.com
    shotacon.dyndns.info
    petto.mooo.com
    kid.dyndns.org

    SHA256 712c488950f27e98bc4ebe5b63e5775498236a179cb4576bf021f8e6e6de0df4
    Campaign Code MYGHOST
    Command and Control 50.7.11.10

    www3.bkav2010.net
    SHA256 b9681c178e087140344e6aec2630c61f6a7be92e97ebbe7ce10528f6f0e6028f
    Campaign Code yxz-tw
    Command and Control 184.22.44.209
    kjd.dyndns.org
    202.82.202.228
    wsi.dyndns.org
    cpcl2006.dyndns-free.com

    SHA256 dc61e089eebf6fa1b3abf637ce105e0d20666aa52d9001f5fd5034815331cd61
    Campaign Code 340_typhoon
    Command and Control beckhammer.xicp.net
    122.10.89.84

    SHA256 6eae10f0b9a62a26b19897f7ba627f92e93e458034939f55f2001835c0e1f1be
    Campaign Code llmacau
    Command and Control 202.82.91.139
    218.103.16.153
    203.218.138.30
    103.246.245.146

    SHA256 8c2cd914de7c125e49019f3826918511150ee4fff8a923da350a99c102b36455
    Campaign Code yxz-kjhkjsxy
    Command and Control 184.22.44.209
    kjd.dyndns.org
    202.82.202.228
    wsi.dyndns.org
    cpcl2006.dyndns-free.com

    SHA256 a8e0ab6b19400eccd3c9aceb183fe7626d5bde7bdf9b8ec8825aa17cc3a213a3
    Campaign Code 340_typhoon
    Command and Control beckhammer.xicp.net
    122.10.89.84

    SHA256 e9971de22a922678fc216e9e3923c7e6b21455ddfbb24eb46e50e1cc7ceacc31
    Campaign Code demo
    Command and Control 122.10.89.84
    beckhammer.xicp.net
    122.10.89.85

    SHA256 0752bbdb0c51a519f17a62dd30a033c224c82168522f2c88949b1a0afc8f9037
    Campaign Code 340-0226
    Command and Control harryleed.dyndns.org
    verolalia.dyndns.org
    jackyson.dyndns.info
    scristioned.dyndns-web.com
    173.231.49.98

    SHA256 4780442f3cc8d3e1888aa6cecbb05d0c49a6755964eba7a8a6a36d6d2a0ef881
    Campaign Code yxz-tw
    Command and Control cpcl2006.dyndns-free.com
    wsi.dyndns.org
    202.82.202.228
    kjd.dyndns.org
    184.22.44.209

    SHA256 bae07b0c3e4e96731360dc4faa49c0d4abe4d3705e768393f21661c82dea13f3
    Campaign Code Alice_vishipel
    Command and Control www.serchers.net
    142.91.252.130
    www.aliancesky.com
    58.64.183.92

    SHA256 7e386ff64be78af18f8a79d01cb75b0438cbcee4647e0a928100bd52ee56db76
    Campaign Code G140509ZA01
    Command and Control 46.251.237.59
    www.tintuchoahau.com

    SHA256 866c698073e4deb66dd83c1ec9567ec03eca9f03775deadb81cc59fdb6cfd446
    Campaign Code 310-pyq
    Command and Control cybertunnel.dyndns.info
    newshappys.dyndns-blog.com
    www.imonju.com
    www.serchers.net
    202.82.202.228

    SHA256 edb45f03dfd52ab58f163ad2ca48f4bc9c4bcb72ea9181d0e0a1d87859f707a6
    Campaign Code 370mymm
    Command and Control 122.10.89.84
    122.10.89.85

    SHA256 3d2c6d48425212eabb886c2e7e89249e4aa8cf4ad9ec3dd22cafb4f879683d8b
    Campaign Code 340-dfa-520
    Command and Control phil-gov.gotdns.org
    scristioned.dyndns-web.com
    asean-star.com
    aseansec.dynalias.org
    113.10.136.18

    SHA256 d9174d6bbcb51d3df186794109cd6b2036f6231cf8733290eadd399bf8137055
    Campaign Code 340-0528
    Command and Control phil-army.gotdns.org
    scristioned.dyndns-web.com
    asean-star.com
    aseansec.dynalias.org
    113.10.136.18

    SHA256 30f1f7e848c79212f70794d718d0f3929c24e0f3d28695a7c85a85c77ab7aac9
    Campaign Code 310-pyq
    Command and Control cybertunnel.dyndns.info
    newshappys.dyndns-blog.com
    www.imonju.com
    www.serchers.net
    202.82.202.228

    SHA256 39dd2381bcd0f47dadf23399254bf1b51a837179e5634328afafe07510f5888a
    Campaign Code 340-0528
    Command and Control phil-army.gotdns.org
    scristioned.dyndns-web.com
    asean-star.com
    aseansec.dynalias.org
    113.10.136.18

    SHA256 e2181b3d47feb5a321fe3b85b08a0245a1e0824b213e568fa4736d529fd5f8c2
    Campaign Code 731
    Command and Control usa-moon.net
    23.234.63.197

    SHA256 c19d3242d43c71f03f5873231444c12a6a11892dd7f0142ff10479f1f718382d
    Campaign Code key0730
    Command and Control usa-moon.net
    23.234.63.197

    SHA256 24bb8e48f37cbd71b2195cff4f52ec304a2ed9d60c28d2afd785e6f32639325f
    Campaign Code bio
    Command and Control usa-moon.net
    23.234.63.197

    SHA256 65c901b19e2eec6b8392100c1073253641a95dd542f39c9ca95755e8a2afde14
    Campaign Code Alice_Spider
    Command and Control www.aliancesky.com
    58.64.183.92
    www.serchers.net
    162.211.181.107

    SHA256 34943d8718d35a633bafefb6f113b3486945ec7dcd19bde11ca3c29feed44af3
    Campaign Code HKDLS
    Command and Control 101.55.121.47
    27.255.64.231
    www.iascas.net
    59.188.247.32

    SHA256 400148084474b709a060b844966cf75301d5f2c2b8ae1048f37f634073ead630
    Campaign Code FUCKU
    Command and Control 101.55.121.47
    118.193.212.61
    www.seachers.net

    SHA256 61a66afac2702276f6bba2cfcab58198fced893ad1da27aef228259869f5383f
    Campaign Code FUCKU
    Command and Control 101.55.121.47
    118.193.212.61
    www.seachers.net

    SHA256 6f039f217d8b3bf6686e298416f084884b9a7ec0ee51f334ecc3f5a2da9145a8
    Campaign Code FUCKU
    Command and Control 101.55.121.47
    118.193.212.61
    www.seachers.net

    SHA256 eae4b429b0b732d49750400e70caef579450d0651373440f536de71d6134c173
    Campaign Code FUCKU
    Command and Control 101.55.121.47
    118.193.212.61
    www.seachers.net

    SHA256 8f7c74a9e1d04ff116e785f3234f80119d68ae0334fb6a5498f6d40eee189cf7
    Campaign Code HKDLS
    Command and Control 101.55.121.47
    27.255.64.231
    www.iascas.net
    59.188.247.32

    SHA256 a462085549f9a1fdeff81ea8190a1f89351a83cf8f6d01ecb5f238541785d4b3
    Campaign Code FUCKU
    Command and Control 101.55.121.47
    118.193.212.61
    www.seachers.net
    SHA256 a8e0ab6b19400eccd3c9aceb183fe7626d5bde7bdf9b8ec8825aa17cc3a213a3
    Campaign Code mm-0807
    Command and Control www.imonju.net
    61.58.31.102
    202.77.181.179

    SHA256 96356db43d7e9a5c3c4e3f9f7ee9a3dba14ad1c7db7367b7f6d664db4f0ef5d7
    Campaign Code jessica-cpt-app
    Command and Control www.serchers.net
    www.aliancesky.com
    162.211.181.107
    58.64.183.92

    SHA256 bd78e106f208cbb8ea9e5902d778514f1fc2d15876fca292971c6695541889a3
    Campaign Code jessica-cpt-app
    Command and Control www.serchers.net
    www.aliancesky.com
    162.211.181.107
    58.64.183.92

    SHA256 96410865d46cda89c7c34c60d485c2378a98acbba7ead5ada90daa02a94ba299
    Campaign Code Alice_erpas
    Command and Control www.boshman09.com
    www.chris201.net
    58.64.183.92

    SHA256 a98db2098fe9e3e203bed8318ae1d71e8a7b68f801613be10f3917baad7b49b2
    Campaign Code jessica-cpt-app
    Command and Control www.serchers.net
    www.aliancesky.com
    162.211.181.107
    58.64.183.92

    SHA256 233af642b3e22613551e087a7cefcf2a530752da6613efc52da7cb957cb8f0f3
    Campaign Code KITY090901
    Command and Control 46.251.237.59
    www.tintuchoahau.com

    SHA256 b1e30dd3ad2c3290adad848f7199e03f365ecf484c44c6c7eaf42f6b323cd30b
    Campaign Code KITY090901
    Command and Control 46.251.237.59
    www.tintuchoahau.com

    SHA256 9a226eeae1fc51a2bc2e72b098d5654238d0cc8eae29c0cdaacb49ae9d997d04
    Campaign Code QY030610
    Command and Control 95.154.195.152
    www.vienclp.com

    SHA256 463c6c6ffb8ecf2df44e294818dd500457807ff126dd658c5fe329c09f43a6e0
    Campaign Code KITY01232
    Command and Control 95.154.195.152
    www.vienclp.com

    SHA256 3a806f8efa338c871b1338a5db8af4128012559d09b06ab997db50a0f90434b1
    Campaign Code KITY01232
    Command and Control 95.154.195.152
    www.vienclp.com

    SHA256 8ce0b29202f3df23ce583040e2ffe79af78e0bb375ce65ec37a6ffe7d49b5bb5
    Campaign Code QY030610
    Command and Control 95.154.195.152
    www.vienclp.com

    SHA256 2551f95845ad83ebc56853442bb75c11517e99fe0196ecb30f80e5b203c9a9ff
    Campaign Code QY030610
    Command and Control 95.154.195.152
    www.vienclp.com

    SHA256 e4a460db653c8df4223ec466a0237943be5de0da92b04a3bf76053fa1401b19e
    Campaign Code QQQQQ
    Command and Control boshman09.com
    chris201.net
    58.64.183.92

    SHA256 49bf19bd2381f5c78eb2d00a62e1b377620705dba0fa843fb8c8d26d92ec52e4
    Campaign Code 36-SC-0114
    Command and Control 103.244.91.16
    162.211.181.26
    101.55.120.165
    beckhammer.xicp.net
    newinfo32.eicp.net

    SHA256 9e5c286fcc47c8346267574ea805cde24b04915f5372f03923c0d6a13290e0ea
    Campaign Code 36-SC-0127
    Command and Control www.interhero.net
    101.55.120.165
    101.55.120.153
    www.babysoal.com
    beckhammer.xicp.net

    SHA256 0201aaa8eda6dedc6c90381e225620cd33fb7b244f76bf229c3dd43feb9bdeaf
    Campaign Code Alice_rosey
    Command and Control 210.209.127.8
    www.boshman09.com
    www.chris201.net
    45.64.113.130

    SHA256 f0304a1f7d87ac413f43a815088895872be0045a33c5f830b4b392a7ce5b8c46
    Campaign Code 340-dfa-1007
    Command and Control usa-moon.net
    aseaneco.org
    103.28.46.96

    SHA256 fd6302a152b0a2eff84b6ef219db5d79b6039043dfd5799ac9a4a0cced58e8bd
    Campaign Code 370my0216
    Command and Control 113.10.222.157
    www.tgecc.org

    SHA256 00c0e0c14835c08d220ef27ef6324df86880167d416ff7183d7df241ffebc3f8
    Campaign Code ooo
    Command and Control www.boshman09.com
    www.chris201.net
    210.209.79.29

    SHA256 0adbf0f6a5c21054e569b2ef68c8c6ae7834a0700672c1f3ec6e50daf49a3a94
    Campaign Code oyf
    Command and Control www.boshman09.com
    www.chris201.net
    210.209.79.29

    SHA256 093e394933c4545ba7019f511961b9a5ab91156cf791f45de074acad03d1a44a
    Campaign Code Alice_rosey
    Command and Control 210.209.127.8
    www.boshman09.com
    www.chris201.net
    45.64.113.130

    SHA256 8e7c198e1eaa5be2d1415be3001c217634ae207b8f912e9a84af6c6016aa467e
    Campaign Code ooo
    Command and Control www.boshman09.com
    www.chris201.net
    210.209.79.29

    SHA256 97d6699e449ddad97cc33e380a4873a7ceb0e8f0f50b5c8f72e6a4ff3dd1009f
    Campaign Code phone
    Command and Control usa-moon.net
    aseaneco.org
    103.252.19.13

    SHA256 b53f98c113e7f72ff5170dcdb2ab2b1c15a02aadb72b2d2710d899aea9b875bd
    Campaign Code phone
    Command and Control usa-moon.net
    aseaneco.org
    103.252.19.13

    SHA256 b2232492776267599307309e9d8874aac25e7cb31b155b0ca05349312690372f
    Campaign Code cyd-zc
    Command and Control 101.55.121.47
    118.193.212.61

    SHA256 64ffe128c61289bec90057c7bf3ff869c329ffcb1afa4c4cd0daed1effabf105
    Campaign Code cyd-zc
    Command and Control 101.55.121.47
    118.193.212.61

**Comment by kbandla** [comment]
woah that was fast @srcr !

**Comment by srcr** [comment]
thx

**Comment by kbandla** [comment]
Added in cc71798ceab473471dd94f1c83de9e1c5d691baa
