### ISSUE TITLE
FIN4 Malware

### ISSUE THREAD

**Issue by chrisddom** [kbandla/APTnotes#158]
Short blog post on FIN4 malware that might be worth adding - http://pwc.blogs.com/cyber_security_updates/2015/06/unfin4ished-business.html

Disclaimer - I co-authored and the blog post itself is fairly short - hopefully we'll publish the full report publicly at some point which is pretty hefty.

Example hash:

https://www.virustotal.com/en/file/d22df444e867fdf647f6757547b2b75968453c3bb398a5d94c5e17a5e57af7f6/analysis/1382609256/ 393f175d3782d4f6b1d215bd0f31a777

**Comment by kbandla** [comment]
Added in b9682bd2639781a09b97725ad74293f13e6090cc. 
Can you update this issue when you have the full report too? Thanks @chrisddom !
