### ISSUE TITLE
SeaDuke / CozyCars

### ISSUE THREAD

**Issue by chrisddom** [kbandla/APTnotes#167]
A couple of related write-ups:

http://www.symantec.com/connect/blogs/forkmeiamfamous-seaduke-latest-weapon-duke-armory
http://researchcenter.paloaltonetworks.com/2015/07/tracking-minidionis-cozycars-new-ride-is-related-to-seaduke/

domain	ff.whitebirchpaper[.]com
domain	visionresearch[.]com
domain	betawebservices.ntnonline[.]com
domain	staff.shasta[.]com
hostname	extranet.qualityplanning[.]com
hostname	secure.hgl[.]com
hostname	illuminatistudios[.]net
ip	103.254.16.168
ip	103.226.132.7
ip	122.228.193.115
md5	01039a95e0a14767784acc8f07035935
md5	0f9534b63cb7af1e3aa34839d7d6e632
md5	2e64131c0426a18c1c363ec69ae6b5f2
md5	70f5574e4e7ad360f4f5c2117a7a1ca7
md5	1dd593ad084e1526c8facce834b0e124
md5	42ffc84c6381a18b1f6d000b94c74b09
md5	719cf63a3922953ceaca6fb4dbed6584
md5	f415470b9f0edc1298b1f6ae75dfaf31
md5	ca770a4c9881afcd610aad30aa53f651
md5	24083e6186bc773cd9c2e70a49309763
md5	b0a9a175e2407352214b2d005253bc0c
md5	b55628a605a5dfb5005c44220ae03b8a
md5	26bd36cc57e30656363ca89910579f63
md5	a9c045c401afb9766e2ca838dc6f47a4
md5	f8cb10b2ee8af6c5555e9cf3701b845f
md5	c8b49b42e6ebb6b977ce7001b6bd96c8
md5	030da7510113c28ee68df8a19c643bb0
md5	e07ef8ffe965ec8b72041ddf9527cac4
md5	4cbd9a0832dcf23867b092de37c10d9d
md5	3a04a5d7ed785daa16f4ebfd3acf0867
md5	9018fa0826f237342471895f315dbf39
md5	98613ecb3afde5fc48ca4204f8363f1d
md5	e00bf9b8261410744c10ae3fe2ce9049
md5	51ea28f4f3fa794d5b207475897b1eef
md5	3195110045f64a3c83fc3e043c46d253
md5	1dd593ad084e1526c8facce834b0e124
url	connectads[.]com
url	kane-consulting[.]net
url	edadmin.kearsney[.]com
url	redbluffchamber[.]com

**Comment by kbandla** [comment]
Added in 9ba10ce772da639bf610ebcd14997ae76dc7f7b5. Thanks @chrisddom !
