### ISSUE TITLE
Add Shiqiang Gang

### ISSUE THREAD

**Issue by thoufique** [kbandla/APTnotes#181]
https://web.archive.org/web/20121030064334/http://blogs.norman.com/2012/security-research/the-shiqiang-gang
https://www.fireeye.com/blog/threat-research/2013/04/new-targeted-attack-on-taiwanese-government-tibetan-activists-open-up-a-can-of-worms-graypigeon-hangame-shiqiang-gang.html
https://blogs.mcafee.com/mcafee-labs/stolen-certificates-shiqiang-gang

**Comment by kbandla** [comment]
Added in the following commits
* 5646b02f1c9340bacfc2696f94c8b3c4f82bc1a6
* b38cfcf1b3269aebb92fc159c924d2a9eaf61ac1
* ac90f1727e8303cba81a86755fd85350c0f5db71
