### ISSUE TITLE
Add MoleRAT

### ISSUE THREAD

**Issue by thoufique** [kbandla/APTnotes#182]
https://web.archive.org/web/20121207083151/http://download01.norman.no/whitepapers/Cyberattack_against_Israeli_and_Palestinian_targets.pdf
https://www.fireeye.com/blog/threat-research/2013/08/operation-molerats-middle-east-cyber-attacks-using-poison-ivy.html
https://www.fireeye.com/blog/threat-research/2014/06/molerats-here-for-spring.html

**Comment by kbandla** [comment]
The first and second links are already added. 

Added in the following commits:
* bc2163392079a1ff111dc468400047e1d641da0d
