### ISSUE TITLE
PlugX Threat	Activity	in	Myanmar

### ISSUE THREAD

**Issue by chrisddom** [kbandla/APTnotes#187]
http://pages.arbornetworks.com/rs/082-KNA-087/images/ASERT%20Threat%20Intelligence%20Brief%202015-05%20PlugX%20Threat%20Activity%20in%20Myanmar.pdf

**Comment by kbandla** [comment]
Added in commit 831bf8526c457cce121b22e443ed8b4100e66b8d. Thanks @chrisddom !
