### ISSUE TITLE
The Spy Kittens Are Back: Rocket Kitten 2

### ISSUE THREAD

**Issue by chrisddom** [kbandla/APTnotes#188]
http://www.trendmicro.com/cloud-content/us/pdfs/security-intelligence/white-papers/wp-the-spy-kittens-are-back.pdf

db2b8f49b4e76c2f538a3a6b222c35547c802cef
29968b0c4157f226761073333ff2e82b588ddf8e
eeb67e663b2fa980c6b228fc2e04304c8992401d
c8096078f0f6c3fbb6d82c5b00211802168f9cba

**Comment by kbandla** [comment]
Added in 9cc7427db04bb011bddef125e35ed4b294c54444. Thanks @chrisddom !
