### ISSUE TITLE
Operation Iron Tiger: How China-Based Actors Shifted Attacks from APAC to US Targets

### ISSUE THREAD

**Issue by gasgas4** [kbandla/APTnotes#194]
blog: 
http://blog.trendmicro.com/trendlabs-security-intelligence/operation-iron-tiger-how-china-based-actors-shifted-attacks-from-apac-to-us-targets/
brief:
http://www.trendmicro.com/vinfo/us/security/news/cyber-attacks/operation-iron-tiger-chinese-cyber-espionage-attacks-on-us-defense-contractors
paper:
http://www.trendmicro.com/cloud-content/us/pdfs/security-intelligence/white-papers/wp-operation-iron-tiger.pdf

**Comment by kbandla** [comment]
Added in commit f0ffb848ec1a725b525a8532bcca48c32f6b07a6. Thanks @gasgas4 !
