### ISSUE TITLE
Targeted Malware Attacks against NGO Linked to Attacks on Burmese Government Websites

### ISSUE THREAD

**Issue by chrisddom** [kbandla/APTnotes#203]
https://citizenlab.org/2015/10/targeted-attacks-ngo-burma/
https://otx.alienvault.com/pulse/5621208f4637f21ecf2aac36/

____

FileHash-MD5	15c926d2602f65be0de65fa9c06aa6c6
hostname	t2[.]mailsecurityservice[.]com
hostname	client[.]mailsecurityservice[.]com
hostname	usafbi[.]websecexp[.]com
hostname	webhttps[.]websecexp[.]com
hostname	usacia[.]websecexp[.]com
hostname	appeur[.]gnway[.]cc
hostname	gmail[.]iyouthen[.]com
hostname	t1[.]mailsecurityservice[.]com
email	wojiaojilao2@sohu[.]com
IPv4	198[.]44[.]190[.]85
FileHash-MD5	c4c147bdfddffec2eea6bf99661e69ee
FileHash-MD5	699b3d90b050cae37f65c855ec7f616a
FileHash-MD5	cec071424d417a095221bf8992819388
FileHash-MD5	53f81415ccedf453d6e3ebcdc142b966
FileHash-MD5	49ceba3347d39870f15f2ab0391af234
FileHash-MD5	5710d567d98a8f4a6682859ce3a35336
FileHash-MD5	6701662097e274f3cd089ceec35471d2
URL	http://client[.]mailsecurityservice[.]com/ViewClient/connect[.]php?n=zxishanchu1106[.]exe

**Comment by kbandla** [comment]
Added in 0c545462b53aa08ac5df411e0533cf40f013f6de. Thanks @chrisddom! :+1:
