### ISSUE TITLE
ROCKET KITTEN: A CAMPAIGN WITH 9 LIVES

### ISSUE THREAD

**Issue by threatcrowd** [kbandla/APTnotes#205]
http://blog.checkpoint.com/wp-content/uploads/2015/11/rocket-kitten-report.pdf

ROCKET KITTEN: A CAMPAIGN WITH 9 LIVES

___

Domains
account[.]login[.]gfimail[.]us
accounts[.]google[.]uk[.]to
account-user[.]com
drive-google[.]co
drives-google[.]co
gfimail[.]us
gmail-member[.]us[.]to
google-setting[.]com
google-verify[.]com
login[.]miicrosoftonline[.]us[.]to
login[.]office365[.]uk[.]to
logins-verify[.]com
login-users[.]com
mail[.]mail2[.]mod[.]gov[.]af[.]mail[.]al
mail-verify[.]com
my[.]idc[.]ac[.]il[.]my[.]to
outlook[.]profile[.]com[.]hmail[.]us
outlook[.]tau[.]ac[.]il[.]mail[.]al
owa[.]inss[.]mises[.]org[.]il
owas[.]haifa[.]ac[.]il[.]info[.]gf
owas[.]haifa[.]us[.]to
profile[.]gmail[.]us[.]to
profile[.]google[.]uk[.]to
profiles[.]faceboek[.]in
©2015 Check Point Software Technologies Ltd[.] All rights reserved | 32
profiles[.]googel[.]com[.]inc[.]gs
profiles[.]googlemembers[.]com[.]home[.]kg
profiles-google[.]uk[.]to
qooqle[.]co
secure[.]www[.]cfr[.]us[.]to
service-logins[.]com
signin-users[.]com
signin-verify[.]com
signs-service[.]com
verification[.]google-it[.]info
video[.]qooqle[.]co
webmail[.]tau[.]ac[.]il[.]us[.]to
webmail[.]technion[.]ac[.]il[.]us[.]to
yahoo-profiles[.]uk[.]to
youtube[.]com[.]now[.]im
IP addresses
[107[.]6[.]181[.]96-127]
[107[.]6[.]172[.]50-62]
[107[.]6[.]154[.]224-231]
107[.]6[.]181[.]116
107[.]6[.]172[.]54
107[.]6[.]172[.]55
107[.]6[.]181[.]114
107[.]6[.]172[.]51
107[.]6[.]172[.]53
107[.]6[.]181[.]100
107[.]6[.]172[.]52
107[.]6[.]154[.]230
5[.]39[.]223[.]227
31[.]192[.]105[.]10
[5[.]145[.]151[.]1-7]
5[.]145[.]151[.]6
[84[.]11[.]146[.]52-63]
84[.]11[.]146[.]55
84[.]11[.]146[.]62
84[.]11[.]146[.]61
[109[.]169[.]22[.]69-72]
[109[.]169[.]61[.]4-8]
109[.]169[.]61[.]8
109[.]169[.]22[.]69
109[.]169[.]22[.]71
109[.]169[.]22[.]72
162[.]223[.]90[.]148
162[.]223[.]91[.]226
162[.]222[.]194[.]51
212[.]118[.]118[.]100

**Comment by kbandla** [comment]
Added in 74da8e6d16a0a47a6853b5da87341a4627b82d58. Thanks @threatcrowd !
