### ISSUE TITLE
Bitdefender APT28 Under the Scope:A Journey into Exfiltrating Intelligence and Government Information

### ISSUE THREAD

**Issue by to4kawa** [kbandla/APTnotes#213]
http://download.bitdefender.com/resources/media/materials/white-papers/en/Bitdefender_In-depth_analysis_of_APT28%E2%80%93The_Political_Cyber-Espionage.pdf

**Comment by kbandla** [comment]
Added in 130ec149659ae2406c1fde01b5133c345c9745c2. Thanks @to4kawa !
