### ISSUE TITLE
Iran-based attackers use back door threats to spy on Middle Eastern targets

### ISSUE THREAD

**Issue by hx1997** [kbandla/APTnotes#218]
http://www.symantec.com/connect/blogs/iran-based-attackers-use-back-door-threats-spy-middle-eastern-targets

**Comment by kbandla** [comment]
Added in 4ffad7f4160b603e88da33494d0c2e31d423288d. Thanks @hx1997 !
Would be nice if Symantec had any *real* data to share about this.
