### ISSUE TITLE
I am Ironman: DEEP PANDA Uses Sakula Malware to Target Organizations in Multiple Sectors

### ISSUE THREAD

**Issue by kbandla** [kbandla/APTnotes#221]
http://www.crowdstrike.com/blog/ironman-deep-panda-uses-sakula-malware-target-organizations-multiple-sectors/

**Comment by beast-fighter** [comment]
previously added and can be found here:  https://app.box.com/s/4dfaheem1io3i71o51rf4lfo2ivotuol
