### ISSUE TITLE
Operation Black Atlas

### ISSUE THREAD

**Issue by gasgas4** [kbandla/APTnotes#222]
paper: http://documents.trendmicro.com/assets/Operation_Black%20Atlas_Technical_Brief.pdf
ioc: http://documents.trendmicro.com/assets/Operation%20Black%20Atlas_Indicators_of_Compromise.pdf

Operation Black Atlas has already spread to a multi-state healthcare provider, dental clinics, a machine manufacturer, a technology company focusing on insurance services, a gas station that has a multi-state presence, and a beauty supply shop.

**Comment by kbandla** [comment]
This is an interesting paper, but its financial malware and not really an apt campaign. I have tagged it as such, this will go into the financial section eventually. Thanks @gasgas4 ! :+1:

**Comment by beast-fighter** [comment]
closing due to no relation to CE and/or APT - tagged and will be added at a later date (if deemed relevant)
