### ISSUE TITLE
Attack on French Diplomat Linked to Operation Lotus Blossom

### ISSUE THREAD

**Issue by gasgas4** [kbandla/APTnotes#223]
URL:  http://researchcenter.paloaltonetworks.com/2015/12/attack-on-french-diplomat-linked-to-operation-lotus-blossom/

"We observed a targeted attack in November directed at an individual working for the French Ministry of Foreign Affairs. The attack involved a spear-phishing email sent to a single French diplomat based in Taipei, Taiwan and contained an invitation to a Science and Technology support group event."

**Comment by beast-fighter** [comment]
previously added
