### ISSUE TITLE
Microsoft assists law enforcement to help disrupt Dorkbot botnets

### ISSUE THREAD

**Issue by to4kawa** [kbandla/APTnotes#225]
https://blogs.technet.microsoft.com/mmpc/2015/12/02/microsoft-assists-law-enforcement-to-help-disrupt-dorkbot-botnets/

**Comment by mtmcgrew** [comment]
Does not seem like APT

**Comment by krmaxwell** [comment]
Good story and worthwhile initiative, but not APT.
