### ISSUE TITLE
 2015 Jun 16 - Operation Lotus Bloom

### ISSUE THREAD

**Issue by to4kawa** [kbandla/APTnotes#228]
thank you for fix 

2015
Jun 16 - Operation Lotus Bloom > Operation Lotus Blossom  

URL:
http://researchcenter.paloaltonetworks.com/2015/06/operation-lotus-blossom/

**Comment by beast-fighter** [comment]
Report was previously added and can be found here: https://app.box.com/s/xhn6ru62qqom1kuxoe3mxnqrtb1sqw2q
