### ISSUE TITLE
RSA GlassRAT report

### ISSUE THREAD

**Issue by threatlead** [kbandla/APTnotes#229]
* https://blogs.rsa.com/wp-content/uploads/2015/11/GlassRAT-final.pdf

"Evidence suggests that the tool is being used as part of a very targeted campaign, focused on Chinese nationals in commercial organizations. GlassRAT’s command and control structure has exhibited brief overlap with C2 that was identified in campaigns associated with malware originally reported in 2012 that targeted government and military organizations in the Pacific Region."
 --- https://blogs.rsa.com/peering-into-glassrat/

**Comment by beast-fighter** [comment]
added in 2cb423a primarily for indicator and named tool recognition
