### ISSUE TITLE
Tracking Rovnix

### ISSUE THREAD

**Issue by to4kawa** [kbandla/APTnotes#233]
https://labs.bitdefender.com/2014/11/tracking-rovnix-2/

In connection with the following:
Konnichiwa, Rovnix! Aggressive Malware Hits Japanese Banks
https://securityintelligence.com/konnichiwa-rovnix-aggressive-malware-hits-japanese-banks/

**Comment by beast-fighter** [comment]
closing due to no relation to CE and/or APT - tagged and will be added at a later date (if deemed relevant)
