### ISSUE TITLE
Uncovering the Seven Pointed Dagger

### ISSUE THREAD

**Issue by to4kawa** [kbandla/APTnotes#235]
Jan 11, 2016
https://asert.arbornetworks.com/wp-content/uploads/2016/01/ASERT-Threat-Intelligence-Brief-Uncovering-the-Seven-Pointed-Dagger.pdf

**Comment by beast-fighter** [comment]
content appears to have originally published in 2015, but not released publicly until 2016 - in an effort to maintain time lines, going to be sticking with release not create date going forward

**Comment by beast-fighter** [comment]
added to box and master CSV in 97178c7
