### ISSUE TITLE
Operation Beebus

### ISSUE THREAD

**Issue by to4kawa** [kbandla/APTnotes#239]
https://www.fireeye.com/blog/threat-research/2013/02/operation-beebus.html

This is old one.

but add from the following website is I think necessary .

http://blog.talosintel.com/2016/01/haystack.html#more

**Comment by beast-fighter** [comment]
both added:
163d6bd - http://blog.talosintel.com/2016/01/haystack.html

4cacb7a - https://www.fireeye.com/blog/threat-research/2013/02/operation-beebus.html
