### ISSUE TITLE
Introducing Hi-Zor RAT

### ISSUE THREAD

**Issue by securitykitten** [kbandla/APTnotes#242]
https://www.fidelissecurity.com/sites/default/files/FTA_1020_Fidelis_Inocnation_FINAL.pdf
http://www.threatgeek.com/2016/01/introducing-hi-zor-rat.html

**Comment by beast-fighter** [comment]
original PDF offline, found here: https://web.archive.org/web/20151217200415/https://www.fidelissecurity.com/sites/default/files/FTA_1020_Fidelis_Inocnation_FINAL.pdf

**Comment by beast-fighter** [comment]
added Fidelis PDF in ade0027
