### ISSUE TITLE
Hacktivism: India vs. Pakistan

### ISSUE THREAD

**Issue by gasgas4** [kbandla/APTnotes#246]
February 11, 2016 by Recorded Future

https://www.recordedfuture.com/india-pakistan-cyber-rivalry/

**Comment by krmaxwell** [comment]
While interesting to me for its own reasons, hacktivism != espionage. I don't think this fits, personally.

**Comment by kbandla** [comment]
Closing, as it does not involve any `targeted` attack. Thanks @gasgas4 !
