### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by sfakiana** [kbandla/APTnotes#249]
Hi all,

Is this repo discontinued?

Cheers

**Comment by kbandla** [comment]
@sfakiana no, it is not discontinued! We are working on retooling the data in a better-accessible way. 
We will be pushing out updates very soon.

**Comment by beast-fighter** [comment]
Nope, we are working on a new platform. Stay tuned...

**Comment by threatcrowd** [comment]
Sounds fun! Let me know if I can do anything to help

**Comment by scotmatson** [comment]
Glad to hear it. Was wondering why nothing has been reported for 2016 as of yet. Thanks for the update.

**Comment by securesean** [comment]
Yes! I love this repo! Keep up the good work!
