### ISSUE TITLE
PLATINUM: Targeted_attacks_in_South_and_Southeast_Asia

### ISSUE THREAD

**Issue by gasgas4** [kbandla/APTnotes#258]
#Microsoft  #APT  #Asia

2016.04.12.PLATINUM_Targeted_attacks_in_South_and_Southeast_Asia

Paper:  http://download.microsoft.com/download/2/2/5/225BFE3E-E1DE-4F5B-A77B-71200928D209/Platinum%20feature%20article%20-%20Targeted%20attacks%20in%20South%20and%20Southeast%20Asia%20April%202016.pdf

**Comment by beast-fighter** [comment]
added in 6563903
