### ISSUE TITLE
PDF storage limitations

### ISSUE THREAD

**Issue by dweinstein** [kbandla/APTnotes#3]
This repository will grow considerably if it continues to store the PDFs, which makes a lot of sense as the original sources can be taken down or wither. 

I am just throwing the idea of using something like [git-annex](https://git-annex.branchable.com/)  out there...

We'd still need a persistent storage backing, but maybe we can use Amazon S3 for that (see http://git-annex.branchable.com/special_remotes/S3/)

**Comment by krmaxwell** [comment]
We're up to 720 MB in my local repo. Might be worth revisiting this.

**Comment by kbandla** [comment]
About time. I'll start prep for the git-annex move this week.

**Comment by dweinstein** [comment]
:+1:

**Comment by krmaxwell** [comment]
https://github.com/blog/1986-announcing-git-large-file-storage-lfs looks like it will be the best solution. Here's hoping :octocat: shows us some :heart: sooner rather than later.

**Comment by dweinstein** [comment]
:+1: it looks like maybe this hit for enterprises only though? maybe they'll show some love to open source projects??

**Comment by kbandla** [comment]
I looked at the pricing model for LFS and it might not work out. So one of the solutions is to move to git-annex, like you pointed. Blobs can be on S3 or a hosting service. Its time to move.

**Comment by stackoverflow84** [comment]
Try hitting up Joel De La Garza @ box. He's been pretty supportive and
accommodating with setting up a sizeable box.com storage account for one of
the other info sec groups I'm in.


   - PM me for his personal contact info.

**Comment by b3nw** [comment]
I can help support this, we utilize this repo far too much not to help out.

Shoot me a note bwalter [a.t] box.com and will get something sorted.

**Comment by dweinstein** [comment]
right on!

**Comment by beast-fighter** [comment]
all reports have been moved to box and will be reflected in the table I will be adding to the repo shortly...stay tuned

**Comment by beast-fighter** [comment]
fixed in the new implementation of box for storage within 393c7f2
