### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by nyx0** [kbandla/APTnotes#67]
This is a cool overview of some apt groups and their links. I don't know if you want to add it or how.
https://apt.securelist.com

**Comment by krmaxwell** [comment]
Maybe in the [papers list](https://github.com/kbandla/APTnotes/blob/master/papers.md)? It's not a paper, exactly, but it is for historical context.

**Comment by nyx0** [comment]
I don't see the "purpose" of papers list, I mean some of them are not technical at all, I only see the word **CYBER** in most of them :p

**Comment by kbandla** [comment]
The papers section is currently incomplete. I have been thinking about renaming it to historical. It is basically a collection of documents that are not directly related to APT, but are background reading. 

Like :
* congressional testimonies
* reports by think tanks about the cyber capabilities of various countries 
* geo-political and conflict analysis, and its connections to targeted cyber attacks
* understanding nation state motives behind cyber attacks, etc

I will probably make these changes soon, somewhere around the time we move over to git-annex.

**Comment by nyx0** [comment]
Done #115
