### ISSUE TITLE
Comfoo

### ISSUE THREAD

**Issue by wootski** [kbandla/APTnotes#78]
http://www.secureworks.com/cyber-threat-intelligence/threats/secrets-of-the-comfoo-masters/

**Comment by kbandla** [comment]
@wootski this report was added in 5691a57274390b5bffbd8fe51600dec866b7c516

**Comment by wootski** [comment]
Apologies, appreciate your work!

**Comment by kbandla** [comment]
thanks for sharing the links @wootski, keep them coming!
