### ISSUE TITLE
Scarab attackers took aim at select Russian targets since 2012

### ISSUE THREAD

**Issue by ant1** [kbandla/APTnotes#80]
http://www.symantec.com/connect/blogs/scarab-attackers-took-aim-select-russian-targets-2012
http://www.symantec.com/content/en/us/enterprise/media/security_response/docs/Scarab_IOCs_January_2015.txt

**Comment by kbandla** [comment]
Added in c1617f58e5e11076f83821db4e375ed90d0c0689. Thanks @ant1 !
