### ISSUE TITLE
Babar: espionage software finally found and put under the microscope

### ISSUE THREAD

**Issue by ant1** [kbandla/APTnotes#89]
https://blog.gdatasoftware.com/blog/article/babar-espionage-software-finally-found-and-put-under-the-microscope.html

**Comment by Neo23x0** [comment]
Rule in Repo

https://github.com/YaraExchange/yarasigs/commit/cfc1ab2df9284007eb5d1f4776d12d5a93c6042b

On Wed, Feb 18, 2015 at 7:14 PM, Antoine <notifications@github.com> wrote:

>
> https://blog.gdatasoftware.com/blog/article/babar-espionage-software-finally-found-and-put-under-the-microscope.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbandla/APTnotes/issues/89>.
>



-- 
Sincerely
Saludos cordiales
Mit freundlichen Grüßen
Florian Roth

PGP Key:
https://www.dropbox.com/sh/lw9ymama8rjukjs/zNQZAujnQM
Key ID:
FE04247D50D1ACC855CB FD26 19E9 BF9E 78C1  D582 FE04 247D 50D1 ACC8

**Comment by krmaxwell** [comment]
Closed by #88
