### ISSUE TITLE
EVIL BUNNY: SUSPECT #4

### ISSUE THREAD

**Issue by ant1** [kbandla/APTnotes#90]
20 november 2014
http://0x1338.blogspot.co.uk/2014/11/hunting-bunnies.html
https://drive.google.com/file/d/0B9Mrr-en8FX4M2lXN1B4eElHcE0/view

**Comment by nyx0** [comment]
I have already done a pull request for a report about Babar, so if it's ok I will modify my pull request to integrate your issues.

**Comment by krmaxwell** [comment]
Closed by #88
