### ISSUE TITLE
SHOOTING  ELEPHANTS

### ISSUE THREAD

**Issue by 7h3rAm** [kbandla/APTnotes#95]
https://drive.google.com/a/sitpub.com/file/d/0B9Mrr-en8FX4dzJqLWhDblhseTA/view?pli=1

**Comment by 7h3rAm** [comment]
Report on Babar from Marion Marschalek

**Comment by nyx0** [comment]
I think you can close this issue, I have already made a pull request  b92a7aecb516ed80f2a74c96b8ba6ecb6060aae9

**Comment by 7h3rAm** [comment]
Sure, I missed that. Thanks.
